version: "3"
services:
  rails:
    build: 
      context: ..
      dockerfile: docker/rails.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../public/uploads:/var/www/public/uploads
      - ../db:/var/www/db